FROM golang:1.15 as builder
RUN wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.33.0
WORKDIR $GOPATH/src/
COPY . hello-again-go/
WORKDIR $GOPATH/src/hello-again-go/
RUN golangci-lint run; exit 0 # this is still a dirty hack to continue execution after code quality check
RUN go test ./...
RUN CGO_ENABLED=0 GOOS=linux go build -installsuffix nocgo -o /app

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app .
EXPOSE 8080
CMD ["./app"]
